#!/bin/bash

echo "🚀 Canvas App - Quick Deploy to Render"
echo "======================================"
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  Go to: https://render.com"
echo "2️⃣  Click: 'Get Started' or 'Sign In'"
echo "3️⃣  Click: 'New +' → 'Web Service'"
echo "4️⃣  Connect your GitHub repo: Ankitgkp/canvas"
echo ""
echo "5️⃣  Configure:"
echo "   Name: canvas-app"
echo "   Build Command: npm install && npm run build"
echo "   Start Command: npm start"
echo ""
echo "6️⃣  Add Environment Variables:"
echo "   DATABASE_URL = postgresql://neondb_owner:npg_lI40GqEChrUH@ep-delicate-dream-adi0uvd5-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo "   JWT_SECRET = B5h0sd4kyx@"
echo "   NODE_ENV = production"
echo ""
echo "7️⃣  Click 'Create Web Service'"
echo ""
echo "✅ Your app will be live at: https://canvas-app.onrender.com"
echo ""
echo "📖 For detailed instructions, see: DEPLOYMENT_COMPLETE.md"
